version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: system-n8n-1
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n

  crawler-api:
    build:
      context: .
    container_name: system-crawler-api-1
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  n8n_data: